"""FluxPay Python SDK.

Thin, safe-by-default payment client for autonomous AI agents.
"""

from .client import (
    CURRENCY_PATTERN,
    MERCHANT_ID_PATTERN,
    Balance,
    FluxPayApiError,
    FluxPayClient,
    FluxPayError,
    FluxPayNetworkError,
    PaymentDetail,
    PaymentResult,
    PaymentStatus,
)
from .signing import (
    FROZEN_VECTORS,
    HEADER_AUTH,
    HEADER_IDEMPOTENCY,
    HEADER_NONCE,
    HEADER_TIMESTAMP,
    SCHEME,
    SEPARATOR,
    FrozenVector,
    canonical_bytes,
    get_frozen_vectors,
    parse_authorization,
    sha256_hex,
    sign,
    validate_idempotency_key,
    validate_nonce,
    validate_timestamp,
    verify,
)

__all__ = [
    "CURRENCY_PATTERN",
    "FROZEN_VECTORS",
    "HEADER_AUTH",
    "HEADER_IDEMPOTENCY",
    "HEADER_NONCE",
    "HEADER_TIMESTAMP",
    "MERCHANT_ID_PATTERN",
    "SCHEME",
    "SEPARATOR",
    "Balance",
    "FluxPayApiError",
    "FluxPayClient",
    "FluxPayError",
    "FluxPayNetworkError",
    "FrozenVector",
    "PaymentDetail",
    "PaymentResult",
    "PaymentStatus",
    "canonical_bytes",
    "get_frozen_vectors",
    "parse_authorization",
    "sha256_hex",
    "sign",
    "validate_idempotency_key",
    "validate_nonce",
    "validate_timestamp",
    "verify",
]
