#!/usr/bin/env bash
# scripts/gen_env.sh
# Purpose: Generate a local-dev .env file from .env.example with cryptographically secure random secrets.
# When it runs: Invoked by 'make env' or 'make setup' during local bootstrap or in automated tests.

set -euo pipefail

OUT_PATH=".env"
FORCE=0

while [ $# -gt 0 ]; do
    case "$1" in
        --out)
            if [ -z "${2:-}" ]; then
                echo "ERROR: --out requires a file path argument." >&2
                exit 1
            fi
            OUT_PATH="$2"
            shift 2
            ;;
        --force)
            FORCE=1
            shift
            ;;
        *)
            echo "ERROR: Unknown argument: $1" >&2
            echo "Usage: $0 [--out PATH] [--force]" >&2
            exit 1
            ;;
    esac
done

if [ -f "$OUT_PATH" ] && [ "$FORCE" -ne 1 ]; then
    echo "ERROR: Refusing to overwrite existing file at '$OUT_PATH'. Use --force (or FORCE=1) to overwrite." >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
EXAMPLE_PATH="$REPO_ROOT/.env.example"

if [ ! -f "$EXAMPLE_PATH" ]; then
    echo "ERROR: Contract file '$EXAMPLE_PATH' not found." >&2
    exit 1
fi

# Generate real random secrets that satisfy Task 3 validators
# FLX_VAULT_MASTER_KEY: Exactly 32 bytes base64-encoded (AES-256 requirement)
VAULT_KEY="$(openssl rand -base64 32)"
# FLX_WEBHOOK_SIGNING_KEY: 64-char hex string (>= 32 chars requirement for HMAC-SHA256)
WEBHOOK_KEY="$(openssl rand -hex 32)"

# Create target directory if needed
TARGET_DIR="$(dirname "$OUT_PATH")"
if [ ! -d "$TARGET_DIR" ]; then
    mkdir -p "$TARGET_DIR"
fi

# Write header
{
    echo "# =============================================================================="
    echo "# LOCAL DEV ONLY — never commit; production values come from Doppler"
    echo "# Generated by scripts/gen_env.sh from .env.example"
    echo "# =============================================================================="
    echo ""
} > "$OUT_PATH"

# Stream .env.example and inject real secrets and local-dev defaults
while IFS= read -r line || [ -n "$line" ]; do
    # Skip existing header comments from .env.example
    if [[ "$line" =~ ^#\ =+ ]] || \
       [[ "$line" =~ ^#\ FluxPay\ Environment\ Contract ]] || \
       [[ "$line" =~ ^#\ Doppler\ usage\ note ]] || \
       [[ "$line" =~ ^#\ In\ production\ and\ CI ]] || \
       [[ "$line" =~ ^#\ This\ \.env\ file\ is\ local-dev ]]; then
        continue
    fi

    # Replace secrets and local-dev service defaults
    if [[ "$line" =~ ^FLX_VAULT_MASTER_KEY= ]]; then
        echo "FLX_VAULT_MASTER_KEY=\"$VAULT_KEY\"" >> "$OUT_PATH"
    elif [[ "$line" =~ ^FLX_WEBHOOK_SIGNING_KEY= ]]; then
        echo "FLX_WEBHOOK_SIGNING_KEY=\"$WEBHOOK_KEY\"" >> "$OUT_PATH"
    elif [[ "$line" =~ ^FLX_PG_DSN= ]]; then
        echo 'FLX_PG_DSN="postgresql://fluxpay:fluxpay@localhost:5432/fluxpay"' >> "$OUT_PATH"
    elif [[ "$line" =~ ^FLX_VALKEY_URL= ]]; then
        echo 'FLX_VALKEY_URL="redis://localhost:6379/0"' >> "$OUT_PATH"
    elif [[ "$line" =~ ^FLX_ENV= ]]; then
        echo 'FLX_ENV="development"' >> "$OUT_PATH"
    else
        echo "$line" >> "$OUT_PATH"
    fi
done < "$EXAMPLE_PATH"

echo "Generated '$OUT_PATH' with cryptographically secure local secrets."
