"""Cryptographic Key Management System (KMS) and Abstract Signer Architecture.

Provides the foundational security boundary for signing Ethereum Virtual Machine (EVM)
transactions and cryptographic messages across Base L2 (chain_id=8453) and Base Sepolia (84532).

Security Invariants & Architectural Laws:
1. THE ABSOLUTE ZERO IN-MEMORY KEY LAW:
   Private keys must NEVER enter application process memory in production. All signing
   operations must be delegated to dedicated Hardware Security Modules (HSMs) or Cloud
   KMS enclaves (AWS KMS, GCP Cloud KMS, Azure Key Vault, YubiHSM 2, Fireblocks MPC).
2. THE FAIL-CLOSED LAW:
   If a KMS service is unreachable, throttled, or returns an unverified signature,
   the platform FAILS CLOSED. It will NEVER fall back to local software keys or bypass
   signature verification.
3. THE SIGNATURE FRESHNESS & NON-CACHEABILITY LAW:
   Cryptographic signatures must NEVER be cached or memoized. Every transaction nonce
   and authorization signature must be freshly generated by the hardware enclave.
4. SINK-LEVEL SECRET REDACTION:
   Private keys, seed phrases, unsigned/signed transaction hex, and raw key IDs are
   STRICTLY forbidden from appearing in logs, metrics, or exception strings. Key IDs are
   obfuscated using truncated SHA-256 digests in structured logging events.
5. MANDATORY LOCAL ADDRESS VERIFICATION:
   Every signature produced by a remote HSM/KMS must be locally verified via public
   key recovery prior to returning raw signed bytes. If the recovered address does not
   match the configured hot-wallet address, the signature is immediately discarded
   and an operational alarm is triggered.
"""

from __future__ import annotations

import hashlib
import hmac
from abc import ABC, abstractmethod
from typing import Any, Final, Protocol, runtime_checkable

from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature
from eth_account import Account
from eth_account._utils.signing import (  # type: ignore[attr-defined]
    encode_transaction,
    serializable_unsigned_transaction_from_dict,
)
from prometheus_client import REGISTRY, CollectorRegistry, Counter, Gauge, Histogram
from web3 import Web3

from fluxpay.shared.errors import IntegrationError
from fluxpay.shared.logging import get_logger

__all__ = [
    "FLX_KMS_BACKEND_UP",
    "FLX_KMS_ERRORS_TOTAL",
    "FLX_KMS_LOCAL_DEV_ACTIVE",
    "FLX_KMS_SIGN_DURATION_SECONDS",
    "FLX_KMS_SIGN_TOTAL",
    "SECP256K1_HALF_N",
    "SECP256K1_N",
    "AddressMismatchError",
    "BaseSigner",
    "KMSError",
    "KmsAccessDeniedError",
    "KmsInvalidSignatureError",
    "KmsKeyNotFoundError",
    "KmsThrottledError",
    "KmsUnavailableError",
    "MPCSigner",
    "SignatureVerificationFailedError",
    "Signer",
    "SignerRegistry",
    "hash_key_id",
]

_logger = get_logger("fluxpay.shared.kms")

# SECP256k1 curve order constants for canonical low-s signature enforcement (EIP-2)
SECP256K1_N: Final[int] = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
SECP256K1_HALF_N: Final[int] = SECP256K1_N // 2


def hash_key_id(key_id: str) -> str:
    """Return a truncated SHA-256 fingerprint of a KMS key identifier.

    Prevents raw AWS ARNs, GCP version paths, or vault URLs from being exposed in logs.
    """
    return hashlib.sha256(key_id.encode("utf-8")).hexdigest()[:16]


# -----------------------------------------------------------------------------
# Prometheus Telemetry Definitions
# -----------------------------------------------------------------------------
def _get_or_create_counter(
    name: str,
    documentation: str,
    labelnames: tuple[str, ...],
    registry: CollectorRegistry = REGISTRY,
) -> Counter:
    """Idempotently register or retrieve a Counter metric."""
    try:
        return Counter(name, documentation, labelnames=labelnames, registry=registry)
    except ValueError:
        collector = getattr(registry, "_names_to_collectors", {}).get(name)
        if isinstance(collector, Counter):
            return collector
        raise


def _get_or_create_gauge(
    name: str,
    documentation: str,
    labelnames: tuple[str, ...],
    registry: CollectorRegistry = REGISTRY,
) -> Gauge:
    """Idempotently register or retrieve a Gauge metric."""
    try:
        return Gauge(name, documentation, labelnames=labelnames, registry=registry)
    except ValueError:
        collector = getattr(registry, "_names_to_collectors", {}).get(name)
        if isinstance(collector, Gauge):
            return collector
        raise


def _get_or_create_histogram(
    name: str,
    documentation: str,
    labelnames: tuple[str, ...],
    buckets: tuple[float, ...],
    registry: CollectorRegistry = REGISTRY,
) -> Histogram:
    """Idempotently register or retrieve a Histogram metric."""
    try:
        return Histogram(
            name, documentation, labelnames=labelnames, buckets=buckets, registry=registry
        )
    except ValueError:
        collector = getattr(registry, "_names_to_collectors", {}).get(name)
        if isinstance(collector, Histogram):
            return collector
        raise


FLX_KMS_SIGN_TOTAL: Final[Counter] = _get_or_create_counter(
    "flx_kms_sign_total",
    "Total KMS signature requests partitioned by backend and outcome",
    ("backend", "outcome"),
)

FLX_KMS_ERRORS_TOTAL: Final[Counter] = _get_or_create_counter(
    "flx_kms_errors_total",
    "Total KMS operational and cryptographic errors by backend and error type",
    ("backend", "type"),
)

FLX_KMS_SIGN_DURATION_SECONDS: Final[Histogram] = _get_or_create_histogram(
    "flx_kms_sign_duration_seconds",
    "KMS signing latency in seconds partitioned by backend",
    ("backend",),
    buckets=(0.010, 0.025, 0.050, 0.100, 0.250, 0.500, 1.000, 2.500, 5.000),
)

FLX_KMS_BACKEND_UP: Final[Gauge] = _get_or_create_gauge(
    "flx_kms_backend_up",
    "KMS backend operational health status (1=up, 0=down)",
    ("backend",),
)

FLX_KMS_LOCAL_DEV_ACTIVE: Final[Gauge] = _get_or_create_gauge(
    "flx_kms_local_dev_active",
    "Critical alarm gauge indicating LocalDevSigner is active in memory (1=active, 0=inactive)",
    (),
)


# -----------------------------------------------------------------------------
# Error Taxonomy: IntegrationError Subclasses
# -----------------------------------------------------------------------------
class KMSError(IntegrationError):
    """Base error for all cryptographic key management failures."""

    def __init__(
        self,
        message: str,
        *,
        code: str,
        details: dict[str, str] | None = None,
        retryable: bool = False,
    ) -> None:
        merged_details = {"code": code}
        if details is not None:
            merged_details.update(details)
        super().__init__(message=message, details=merged_details)
        self.code = code
        self.retryable = retryable


class KmsUnavailableError(KMSError):
    """Raised when KMS/HSM service endpoint is temporarily unreachable or times out."""

    def __init__(
        self,
        message: str = "KMS service temporarily unavailable",
        *,
        details: dict[str, str] | None = None,
    ) -> None:
        super().__init__(message, code="KMS_UNAVAILABLE", details=details, retryable=True)


class KmsAccessDeniedError(KMSError):
    """Raised when IAM credentials or vault access policy denies key usage (fail-closed)."""

    def __init__(
        self,
        message: str = "KMS access denied by security policy",
        *,
        details: dict[str, str] | None = None,
    ) -> None:
        super().__init__(message, code="KMS_ACCESS_DENIED", details=details, retryable=False)


class KmsThrottledError(KMSError):
    """Raised when KMS rate limits or API TPS quotas are exceeded (retry with jitter)."""

    def __init__(
        self,
        message: str = "KMS signing request throttled by provider",
        *,
        details: dict[str, str] | None = None,
    ) -> None:
        super().__init__(message, code="KMS_THROTTLED", details=details, retryable=True)


class KmsInvalidSignatureError(KMSError):
    """Raised when KMS returns malformed DER ASN.1 data or invalid elliptic curve scalars."""

    def __init__(
        self,
        message: str = "KMS returned malformed or unparseable signature",
        *,
        details: dict[str, str] | None = None,
    ) -> None:
        super().__init__(message, code="KMS_INVALID_SIGNATURE", details=details, retryable=False)


class KmsKeyNotFoundError(KMSError):
    """Raised when requested key ID, alias, or key version is missing from the vault."""

    def __init__(
        self,
        message: str = "KMS signing key was not found",
        *,
        details: dict[str, str] | None = None,
    ) -> None:
        super().__init__(message, code="KMS_KEY_NOT_FOUND", details=details, retryable=False)


class AddressMismatchError(KMSError):
    """Raised when locally recovered address does not match expected EIP-55 address (CRITICAL)."""

    def __init__(
        self,
        message: str = "Recovered signer address does not match expected address",
        *,
        details: dict[str, str] | None = None,
    ) -> None:
        super().__init__(message, code="ADDRESS_MISMATCH", details=details, retryable=False)


class SignatureVerificationFailedError(KMSError):
    """Raised when signature fails mathematical verification against public key (CRITICAL)."""

    def __init__(
        self,
        message: str = "Cryptographic signature verification failed",
        *,
        details: dict[str, str] | None = None,
    ) -> None:
        super().__init__(
            message,
            code="SIGNATURE_VERIFICATION_FAILED",
            details=details,
            retryable=False,
        )


# -----------------------------------------------------------------------------
# Signer Protocol & Base Implementation
# -----------------------------------------------------------------------------
@runtime_checkable
class Signer(Protocol):
    """Abstract protocol for signing Base L2 EVM transactions and messages."""

    async def get_address(self) -> str:
        """Return EIP-55 checksummed Ethereum address."""
        ...

    async def sign_transaction(self, tx: dict[str, Any]) -> bytes:
        """Sign an EIP-1559 transaction dict and return raw signed transaction bytes."""
        ...

    async def sign_message(self, message: bytes) -> bytes:
        """Sign an arbitrary byte payload conforming to EIP-191 personal_sign."""
        ...

    async def sign_typed_data(self, typed_data: dict[str, Any]) -> bytes:
        """Sign an EIP-712 structured typed data object."""
        ...


class BaseSigner(ABC):
    """Abstract base class implementing shared EVM cryptographic operations and security laws.

    Provides canonical EIP-2 low-s normalization, recovery ID determination,
    address verification, and sanitized string representations.
    """

    def __init__(self, *, address: str) -> None:
        self._address: Final[str] = Web3.to_checksum_address(address)

    @property
    def address(self) -> str:
        """Return EIP-55 checksummed address (supports legacy TxSigner interface)."""
        return self._address

    async def get_address(self) -> str:
        """Return EIP-55 checksummed address conforming to Signer protocol."""
        return self._address

    @abstractmethod
    async def sign_transaction(self, tx: dict[str, Any]) -> bytes:
        """Sign an EIP-1559 transaction dict and return raw signed transaction bytes."""
        ...

    @abstractmethod
    async def sign_message(self, message: bytes) -> bytes:
        """Sign an arbitrary byte payload conforming to EIP-191."""
        ...

    @abstractmethod
    async def sign_typed_data(self, typed_data: dict[str, Any]) -> bytes:
        """Sign an EIP-712 structured typed data object."""
        ...

    @staticmethod
    def normalize_s(s: int) -> int:
        """Enforce canonical low-s values to prevent transaction malleability (EIP-2).

        Args:
            s: Raw signature scalar s.

        Returns:
            Normalized s where s <= SECP256K1_N // 2.
        """
        if s > SECP256K1_HALF_N:
            return SECP256K1_N - s
        return s

    @staticmethod
    def parse_der_or_raw_signature(sig_bytes: bytes) -> tuple[int, int]:
        """Parse raw 64-byte (r || s) or DER ASN.1 ECDSA signature.

        Args:
            sig_bytes: Raw signature bytes returned by KMS/HSM.

        Returns:
            Tuple of integer scalars (r, s).

        Raises:
            KmsInvalidSignatureError: If signature is malformed or scalars out of range.
        """
        try:
            if len(sig_bytes) == 64:
                r = int.from_bytes(sig_bytes[:32], "big")
                s = int.from_bytes(sig_bytes[32:], "big")
            else:
                r, s = decode_dss_signature(sig_bytes)
        except Exception as exc:
            raise KmsInvalidSignatureError(
                message=f"Failed to parse DER/raw signature: {exc}",
                details={"len": str(len(sig_bytes))},
            ) from exc

        # Cryptographic range check: 1 <= r, s < SECP256K1_N
        if not (1 <= r < SECP256K1_N and 1 <= s < SECP256K1_N):
            raise KmsInvalidSignatureError(
                message="Signature scalars r or s fall outside SECP256k1 valid range",
                details={
                    "r_valid": str(1 <= r < SECP256K1_N),
                    "s_valid": str(1 <= s < SECP256K1_N),
                },
            )

        return r, s

    def determine_recovery_id(self, digest: bytes, r: int, s: int) -> int:
        """Compute the Ethereum ECDSA recovery ID (v = 0 or 1) by trial recovery.

        Verifies that the recovered address matches the configured signer address.
        Constant-time string comparison is enforced via hmac.compare_digest.

        Args:
            digest: 32-byte keccak256 hash that was signed.
            r: Elliptic curve scalar r.
            s: Normalized low-s scalar.

        Returns:
            Recovery identifier v (0 or 1).

        Raises:
            AddressMismatchError: If neither candidate v recovers to the configured address.
        """
        for candidate_v in (0, 1):
            try:
                recovered = Account._recover_hash(digest, vrs=(candidate_v, r, s))
                if hmac.compare_digest(recovered.lower(), self._address.lower()):
                    return candidate_v
            except Exception as exc:
                _logger.debug(
                    "kms_recovery_id_failed_candidate",
                    candidate_v=candidate_v,
                    error=str(exc),
                )
                continue

        raise AddressMismatchError(
            message="KMS signature failed local address recovery check",
            details={"configured_address": self._address},
        )

    @staticmethod
    def hash_eip1559_transaction(tx_dict: dict[str, Any]) -> tuple[dict[str, Any], bytes]:
        """Compute the canonical 32-byte signing hash of an unsigned EIP-1559 transaction dict.

        Args:
            tx_dict: Unsigned transaction dictionary.

        Returns:
            Tuple of (clean_tx_dict_without_from, 32_byte_tx_hash).
        """
        clean_tx = {k: v for k, v in tx_dict.items() if k != "from"}
        unsigned_tx = serializable_unsigned_transaction_from_dict(clean_tx)
        return clean_tx, bytes(unsigned_tx.hash())

    def assemble_eip1559_signed_transaction(
        self,
        unsigned_tx_dict: dict[str, Any],
        v: int,
        r: int,
        s: int,
    ) -> bytes:
        """RLP-encode signed EIP-1559 Type-2 transaction bytes.

        Args:
            unsigned_tx_dict: Transaction payload dictionary.
            v: Recovery ID (0 or 1).
            r: Elliptic curve scalar r.
            s: Normalized low-s scalar.

        Returns:
            Raw serialized transaction bytes ready for broadcast.
        """
        clean_tx = {k: v for k, v in unsigned_tx_dict.items() if k != "from"}
        unsigned_tx = serializable_unsigned_transaction_from_dict(clean_tx)
        signed_bytes = encode_transaction(unsigned_tx, vrs=(v, r, s))
        return bytes(signed_bytes)

    @staticmethod
    def assemble_65byte_signature(r: int, s: int, v: int) -> bytes:
        """Assemble canonical 65-byte Ethereum signature (r || s || v).

        Args:
            r: Scalar r.
            s: Normalized scalar s.
            v: Recovery identifier (0/1 or 27/28).

        Returns:
            65 bytes containing (r: 32 bytes, s: 32 bytes, v: 1 byte).
        """
        standard_v = 27 + v if v in (0, 1) else v
        return r.to_bytes(32, "big") + s.to_bytes(32, "big") + bytes([standard_v])

    def __repr__(self) -> str:
        """Redact sensitive fields; only expose class name and verified address."""
        return f"<{self.__class__.__name__} address='{self._address}'>"

    def __str__(self) -> str:
        return f"{self.__class__.__name__}({self._address})"


# -----------------------------------------------------------------------------
# MPC Signer Abstract Interface
# -----------------------------------------------------------------------------
class MPCSigner(BaseSigner, ABC):
    """Abstract base class for Multi-Party Computation (MPC) signing backends.

    Handles asynchronous distributed threshold signing workflows (Fireblocks, Qredo, Copper).
    """

    @abstractmethod
    async def initiate_signing(self, message_hash: bytes) -> str:
        """Initiate asynchronous MPC signing operation and return an operation ID.

        Args:
            message_hash: 32-byte keccak256 digest to sign.

        Returns:
            External MPC operation or transaction tracking ID.
        """
        ...

    @abstractmethod
    async def poll_signature(
        self,
        operation_id: str,
        *,
        timeout_s: float = 30.0,
    ) -> tuple[int, int, int]:
        """Poll MPC threshold nodes until signature quorum is reached.

        Args:
            operation_id: External operation tracking ID.
            timeout_s: Maximum duration to wait before timing out.

        Returns:
            Tuple of (v, r, s).
        """
        ...


# -----------------------------------------------------------------------------
# Signer Registry for Zero-Downtime Key Rotation
# -----------------------------------------------------------------------------
class SignerRegistry:
    """Thread-safe registry mapping key identifiers to active Signer instances.

    Facilitates zero-downtime key rotation:
    - Primary key is used for signing all new outbound transactions.
    - Secondary/previous keys remain registered to verify in-flight authorizations.
    """

    def __init__(self, *, primary_key_id: str | None = None) -> None:
        self._signers: dict[str, Signer] = {}
        self._primary_key_id: str | None = primary_key_id

    def register(self, key_id: str, signer: Signer, *, is_primary: bool = False) -> None:
        """Register a Signer instance under a specific key identifier.

        Args:
            key_id: Unique key identifier or alias.
            signer: Initialized Signer instance.
            is_primary: Whether this key is the default signing key.
        """
        self._signers[key_id] = signer
        if is_primary or self._primary_key_id is None:
            self._primary_key_id = key_id

    def get(self, key_id: str) -> Signer:
        """Retrieve a registered Signer by key ID.

        Args:
            key_id: Key identifier.

        Returns:
            Matching Signer instance.

        Raises:
            KmsKeyNotFoundError: If key_id is not registered.
        """
        if key_id not in self._signers:
            raise KmsKeyNotFoundError(
                message=f"No signer registered for key ID: {hash_key_id(key_id)}",
                details={"key_fingerprint": hash_key_id(key_id)},
            )
        return self._signers[key_id]

    def get_primary(self) -> Signer:
        """Retrieve the primary signing key instance.

        Returns:
            Primary Signer instance.

        Raises:
            KmsKeyNotFoundError: If no primary key is configured.
        """
        if self._primary_key_id is None or self._primary_key_id not in self._signers:
            raise KmsKeyNotFoundError(message="No primary signer registered in SignerRegistry")
        return self._signers[self._primary_key_id]

    def set_primary(self, key_id: str) -> None:
        """Promote an existing registered key to primary status.

        Args:
            key_id: Key identifier to promote.

        Raises:
            KmsKeyNotFoundError: If key_id is not already registered.
        """
        if key_id not in self._signers:
            raise KmsKeyNotFoundError(
                message=f"Cannot promote unregistered key ID: {hash_key_id(key_id)}",
                details={"key_fingerprint": hash_key_id(key_id)},
            )
        self._primary_key_id = key_id

    def has_key(self, key_id: str) -> bool:
        """Check whether a key ID is currently registered."""
        return key_id in self._signers

    def list_keys(self) -> list[str]:
        """Return list of all registered key IDs."""
        return list(self._signers.keys())
