"""Dual-Authorization: 2-Man Rule for Held Payments (Block H, Part 4).

==============================================================================
CONVERGENCE ESSAY: TWO-PHASE VOTE/SETTLE RATIONALE & CRASH-WINDOW SWEEP
==============================================================================
A fundamental safety law of FluxPay is that MONEY MOVES ONLY THROUGH TASK 31'S
SETTLEMENT DOOR (settle_approved). Approval orchestration does not move ledger
balances; it evaluates human governance consensus and safely unlocks the
exact-once settlement door.

The execution is intentionally split into two distinct operational phases:
Phase 1: Quorum Vote Commit (Database UnitOfWork)
- Locks the payment_holds record FOR UPDATE (asserting 'pending' state).
- Enforces role discipline ('admin' only) and self-vote exclusion (UNIQUE constraint
  on (hold_id, voter_sub)).
- Commits the approver's vote and audit row (`hold.vote`) atomically.
- If threshold is reached (approves >= 2), updates status to 'approved' and records
  `hold.approve2` audit row, committing the UnitOfWork.

Phase 2: Post-Commit Settlement Replay
- Because Task 31's settle_approved manages its own transaction boundaries across
  the ledger store and outbox, nesting it inside Phase 1's UnitOfWork would trigger
  transaction nesting deadlocks and connection starvation.
- Therefore, settlement executes immediately AFTER Phase 1 commits.
- If a server process crashes, hardware fails, or network partitions in the microsecond
  window between Phase 1 commit ('approved') and Phase 2 completion:
  The payment hold remains in status='approved', but the financial transaction has not
  settled (idempotency key remains PENDING).
- The ApprovalsWorker continuous poll loop detects approved holds older than the grace
  period (default 60s) and executes a crash-heal sweep:
  1. It performs an idempotency probe via `idempotency.lookup(conn, agent_id, idem_key)`.
  2. If the reservation is COMPLETED (replay outcome), the payment was already settled
     prior to the crash; the sweep safely skips without redundant work.
  3. If the reservation is PENDING, the sweep calls Task 31's `settle_approved`, records
     the `hold.settled` audit row, and emits operator notifications.
Task 31's deterministic transaction ID and reservation claim make this healing pass
strictly idempotent and crash-proof.

==============================================================================
ARCHITECTURAL DECISIONS & DOMAIN LAWS
==============================================================================
1. REJECT-TERMINATES ASYMMETRY (PRODUCT DECISION):
   Rejections are terminal immediately (REJECTS_TERMINAL = True). If any approver
   flags fraud, sanctions breach, or critical risk, the hold is terminated immediately
   regardless of whether another approver has voted 'approve'. Approvals must never race
   a known rejection. Two approvals + one rejection resolves decisively as REJECTED.

2. ADMIN-ONLY VOTER LAW & SEPARATION OF DUTIES:
   Only administrators possessing role 'admin' may vote on money movement. Support
   operators may inspect held queues, review audit trails, and assist merchants, but
   are strictly forbidden from approving fund releases (403 ForbiddenError).

3. "THE AGENT IS NOT A PARTY" (2-MAN RULE INTERPRETATION):
   Unlike human expense systems where creator != approver, holds in FluxPay are
   system-generated by autonomous AI agents when spending ceilings or velocity limits
   are breached. The agent is not a human party. The 2-man rule is strictly enforced
   as TWO DISTINCT HUMAN ADMINISTRATORS (DB uniqueness on (hold_id, voter_sub)).

4. NOTIFICATION DEDUP MARKER (IN-TABLE COLUMN):
   `payment_holds.notified_at` provides an in-table deduplication marker. An additive
   column avoids foreign key overhead and join latency on high-frequency hold queries.
   Crash between notification dispatch and DB update results in at most one duplicate
   alert, which is acceptable at-least-once operational semantics.

5. WHY NO SHARED APPROVAL FRAMEWORK WITH TREASURY (TASK 47 NOTE):
   Treasury cold payouts (Task 47) also implement a 2-man rule, but operate against
   different tables, distinct risk profiles, different audit retention requirements,
   and independent operational cadences. Sharing an abstract "approval framework" would
   tightly couple merchant risk quarantine with internal treasury management.
   Boring code duplication wins at this scale.

6. TASK 43 NOTIFIER SEAM:
   AdminNotifier Protocol defines the decoupled seam for operator notifications.
   Task 42 ships with a logging stub; Task 43 implements the production alerting
   transports (Slack, Telegram, Email) against this exact Protocol.
"""

from __future__ import annotations

import asyncio
from collections.abc import Callable, Coroutine, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Any, Final, Literal, Protocol, runtime_checkable
from uuid import UUID

import asyncpg  # type: ignore[import-untyped]
import orjson

from fluxpay.audit import audit
from fluxpay.payments.service import PaymentService, deterministic_tx_id
from fluxpay.risk.quarantine import HoldRecord
from fluxpay.shared.errors import (
    ERROR_REGISTRY,
    FluxPayError,
    ForbiddenError,
    NotFoundError,
    ValidationError,
)
from fluxpay.shared.events import EventBus, EventType, make_event
from fluxpay.shared.idempotency import (
    ReservationOutcome,
)
from fluxpay.shared.idempotency import (
    fail as idempotency_fail,
)
from fluxpay.shared.idempotency import (
    lookup as idempotency_lookup,
)
from fluxpay.shared.logging import get_logger
from fluxpay.shared.uow import UnitOfWork
from fluxpay.workers.base import Worker

logger = get_logger("fluxpay.approvals")

# ==============================================================================
# POLICY CONSTANTS (MODULE-LEVEL, FROZEN)
# ==============================================================================
VOTES_REQUIRED: Final[int] = 2
REJECTS_TERMINAL: Final[bool] = True


# ==============================================================================
# ERROR TAXONOMY APPEND (TASK 42)
# ==============================================================================
class HoldNotPendingError(FluxPayError):
    """Payment hold is no longer pending (already decided, settled, or rejected)."""

    code: str = "hold_not_pending"
    status: int = 409
    retryable: bool = False
    client_message: str = "payment hold is not in pending status"


ERROR_REGISTRY[HoldNotPendingError.code] = HoldNotPendingError


# ==============================================================================
# PURE DECISION POLICY FUNCTIONS (TESTABLE IN ISOLATION)
# ==============================================================================
def decide_from_votes(votes_for: int, votes_against: int) -> str:
    """Evaluate vote counts against the 2-man rule quorum policy.

    Asymmetry Rule:
    - If votes_against >= 1 and REJECTS_TERMINAL: outcome is 'rejected'.
    - If votes_for >= VOTES_REQUIRED: outcome is 'approved_settled'.
    - Otherwise: outcome is 'counted' (awaiting second voter).
    """
    if REJECTS_TERMINAL and votes_against >= 1:
        return "rejected"
    if votes_for >= VOTES_REQUIRED:
        return "approved_settled"
    return "counted"


def check_voter_role(voter_role: str) -> None:
    """Enforce administrator role for approval voting.

    Raises:
        ForbiddenError: If voter does not have 'admin' role.
    """
    if voter_role != "admin":
        raise ForbiddenError(message="insufficient permissions: admin role required to vote")


def classify_vote(
    *,
    already_voted: bool,
    votes_for: int,
    votes_against: int,
) -> str:
    """Classify vote state into a VoteOutcome status string."""
    if already_voted:
        return "already_voted"
    return decide_from_votes(votes_for, votes_against)


# ==============================================================================
# VALUE OBJECTS & PROTOCOLS
# ==============================================================================
VoteStatus = Literal["counted", "approved_settled", "rejected", "already_voted"]


@dataclass(frozen=True, slots=True)
class VoteOutcome:
    """Immutable outcome of submitting an approval vote."""

    status: VoteStatus
    votes_for: int
    votes_against: int

    def to_dict(self) -> dict[str, Any]:
        """Produce JSON-serializable dictionary for HTTP wire response."""
        return {
            "status": self.status,
            "votes_for": self.votes_for,
            "votes_against": self.votes_against,
        }


@runtime_checkable
class AdminNotifier(Protocol):
    """Notification seam for operator payment hold alerts (Task 43 contract).

    Decouples voting and settlement orchestration from specific transport sinks.
    Task 43 implements this Protocol for Telegram, Slack, and email channels.
    """

    async def notify_hold_pending(self, hold: HoldRecord) -> None:
        """Notify operators that a payment hold requires review."""
        ...

    async def notify_hold_settled(self, hold: HoldRecord, outcome: Any) -> None:
        """Notify operators that a payment hold was approved and settled."""
        ...

    async def notify_hold_rejected(self, hold: HoldRecord, outcome: Any) -> None:
        """Notify operators that a payment hold was rejected."""
        ...


class LoggingAdminNotifier:
    """Default logging-stub implementation of AdminNotifier until Task 43 ships."""

    async def notify_hold_pending(self, hold: HoldRecord) -> None:
        logger.info(
            "admin_notify_hold_pending",
            hold_id=str(hold.hold_id),
            agent_id=str(hold.agent_id),
            amount_minor=hold.amount_minor,
            currency=hold.currency,
        )

    async def notify_hold_settled(self, hold: HoldRecord, outcome: Any) -> None:
        logger.info(
            "admin_notify_hold_settled",
            hold_id=str(hold.hold_id),
            agent_id=str(hold.agent_id),
            outcome=str(outcome),
        )

    async def notify_hold_rejected(self, hold: HoldRecord, outcome: Any) -> None:
        logger.info(
            "admin_notify_hold_rejected",
            hold_id=str(hold.hold_id),
            agent_id=str(hold.agent_id),
            outcome=str(outcome),
        )


# ==============================================================================
# APPROVAL SERVICE
# ==============================================================================
class ApprovalService:
    """Orchestrates 2-man quorum voting, hold state transitions, and settlement."""

    def __init__(
        self,
        pool: asyncpg.Pool,
        bus: EventBus,
        notifier: AdminNotifier | None = None,
        payments: PaymentService | None = None,
    ) -> None:
        self._pool = pool
        self._bus = bus
        self._notifier: AdminNotifier = notifier if notifier is not None else LoggingAdminNotifier()
        self._payments = payments

    async def submit_vote(
        self,
        *,
        hold_id: UUID,
        voter_sub: str,
        voter_role: str,
        vote: str,
        note: str = "",
    ) -> VoteOutcome:
        """Submit a vote on a quarantined payment hold.

        Enforces:
        - Admin role verification (403 ForbiddenError on non-admin).
        - Vote validation ('approve' | 'reject').
        - Hold existence and status='pending' (409 HoldNotPendingError if not pending).
        - Self/duplicate vote prevention via DB UNIQUE(hold_id, voter_sub).
        - Atomic UoW committing vote + decide + audit.
        - Two-phase settlement execution after commit.
        """
        # 1. Role validation (separation of duties)
        check_voter_role(voter_role)

        # 2. Vote input validation
        if vote not in ("approve", "reject"):
            raise ValidationError(
                message="Request payload failed validation.",
                details={"field": "vote", "reason": "must be 'approve' or 'reject'"},
            )

        # 3. Note truncation policy: max 200 characters app-side
        truncated_note = note[:200]

        hold: HoldRecord | None = None
        action_after_commit: str = "counted"
        votes_for: int = 0
        votes_against: int = 0

        # Phase 1: Unit of Work transaction
        try:
            async with UnitOfWork(self._pool) as uow:
                # Assert hold exists and is in 'pending' status with row-level lock
                row = await uow.connection.fetchrow(
                    """
                    SELECT
                        hold_id, agent_id, idem_key, amount_minor, currency,
                        reason, status, payload, created_at, updated_at
                    FROM payment_holds
                    WHERE hold_id = $1
                    FOR UPDATE;
                    """,
                    hold_id,
                )
                if row is None:
                    raise NotFoundError(
                        details={"hold_id": str(hold_id)},
                        message="The requested payment hold was not found.",
                    )

                hold_status = str(row["status"])
                if hold_status != "pending":
                    raise HoldNotPendingError(
                        details={"hold_id": str(hold_id), "status": hold_status},
                        message=f"Hold {hold_id} is in status '{hold_status}', not 'pending'.",
                    )

                raw_payload = row["payload"]
                payload_data: dict[str, Any] = (
                    orjson.loads(raw_payload)
                    if isinstance(raw_payload, (str, bytes))
                    else dict(raw_payload)
                )

                hold = HoldRecord(
                    hold_id=row["hold_id"],
                    agent_id=row["agent_id"],
                    idem_key=row["idem_key"],
                    amount_minor=row["amount_minor"],
                    currency=row["currency"],
                    reason=row["reason"],
                    status=hold_status,
                    created_at=row["created_at"],
                    payload=payload_data,
                    updated_at=row["updated_at"],
                )

                # Query existing votes
                existing_votes = await uow.connection.fetch(
                    """
                    SELECT voter_sub, vote
                    FROM approval_votes
                    WHERE hold_id = $1;
                    """,
                    hold_id,
                )
                voters = {r["voter_sub"] for r in existing_votes}
                cur_for = sum(1 for r in existing_votes if r["vote"] == "approve")
                cur_against = sum(1 for r in existing_votes if r["vote"] == "reject")

                # Duplicate vote check (application-level guard)
                if voter_sub in voters:
                    return VoteOutcome(
                        status="already_voted",
                        votes_for=cur_for,
                        votes_against=cur_against,
                    )

                # Insert new vote record (database-level UNIQUE constraint guard)
                await uow.connection.execute(
                    """
                    INSERT INTO approval_votes (hold_id, voter_sub, vote, note, voted_at)
                    VALUES ($1, $2, $3, $4, now());
                    """,
                    hold_id,
                    voter_sub,
                    vote,
                    truncated_note,
                )

                # Audit vote recording (commits atomically with UoW)
                await audit.record(
                    uow.connection,
                    actor_sub=voter_sub,
                    actor_role=voter_role,
                    action="hold.vote",
                    target_type="agent",
                    target_id=str(hold.agent_id),
                    details={
                        "hold_id": str(hold_id),
                        "vote": vote,
                        "note": truncated_note,
                    },
                )

                votes_for = cur_for + (1 if vote == "approve" else 0)
                votes_against = cur_against + (1 if vote == "reject" else 0)

                # Evaluate quorum decision
                if REJECTS_TERMINAL and votes_against >= 1:
                    # Reject path: single rejection kills hold immediately
                    await uow.connection.execute(
                        """
                        UPDATE payment_holds
                        SET status = 'rejected', updated_at = now()
                        WHERE hold_id = $1 AND status = 'pending';
                        """,
                        hold_id,
                    )
                    # Task 11 idempotency fail (marks reservation FAILED)
                    await idempotency_fail(uow.connection, hold.agent_id, hold.idem_key)

                    # Audit reject recording
                    await audit.record(
                        uow.connection,
                        actor_sub=voter_sub,
                        actor_role=voter_role,
                        action="hold.reject",
                        target_type="agent",
                        target_id=str(hold.agent_id),
                        details={
                            "hold_id": str(hold_id),
                            "reason": "rejected_by_approver",
                            "note": truncated_note,
                        },
                    )
                    action_after_commit = "reject"

                elif votes_for >= VOTES_REQUIRED:
                    # Approve path: 2-man threshold reached
                    await uow.connection.execute(
                        """
                        UPDATE payment_holds
                        SET status = 'approved', updated_at = now()
                        WHERE hold_id = $1 AND status = 'pending';
                        """,
                        hold_id,
                    )
                    # Audit approve2 recording
                    await audit.record(
                        uow.connection,
                        actor_sub=voter_sub,
                        actor_role=voter_role,
                        action="hold.approve2",
                        target_type="agent",
                        target_id=str(hold.agent_id),
                        details={
                            "hold_id": str(hold_id),
                            "votes_for": votes_for,
                        },
                    )
                    action_after_commit = "settle"
                else:
                    action_after_commit = "counted"

        except asyncpg.UniqueViolationError:
            # Concurrent race for the same voter identity tripped DB constraint.
            # UoW aborted cleanly; no audit rows committed for failed branch.
            async with self._pool.acquire() as conn:
                vote_rows = await conn.fetch(
                    "SELECT vote FROM approval_votes WHERE hold_id = $1;", hold_id
                )
                vf = sum(1 for r in vote_rows if r["vote"] == "approve")
                va = sum(1 for r in vote_rows if r["vote"] == "reject")
                return VoteOutcome(status="already_voted", votes_for=vf, votes_against=va)

        if hold is None:
            raise RuntimeError("Unexpected failure: hold record was not loaded")

        # Phase 2: Post-commit settlement and notification execution
        if action_after_commit == "reject":
            # Rejection broadcast & notification
            to_merchant = str(hold.payload.get("to_merchant") or hold.payload.get("merchant") or "")
            amount_minor = int(hold.payload.get("amount_minor") or hold.amount_minor)
            fee_minor = int(hold.payload.get("fee_minor") or 0)
            total_minor = int(hold.payload.get("total_minor") or hold.amount_minor)
            currency = str(hold.payload.get("currency") or hold.currency)
            tx_id = deterministic_tx_id(hold.agent_id, hold.idem_key)

            failed_event = make_event(
                type=EventType.PAYMENT_FAILED,
                payload={
                    "tx_id": str(tx_id),
                    "payment_id": str(tx_id),
                    "agent_id": str(hold.agent_id),
                    "merchant": to_merchant,
                    "amount": amount_minor,
                    "fee": fee_minor,
                    "total": total_minor,
                    "currency": currency,
                    "reason": "rejected_by_approver",
                },
                producer="fluxpay.approvals",
            )
            await self._bus.publish(failed_event)
            await self._notifier.notify_hold_rejected(hold, outcome="rejected")
            return VoteOutcome(
                status="rejected",
                votes_for=votes_for,
                votes_against=votes_against,
            )

        if action_after_commit == "settle":
            # Settlement through Task 31's settle_approved door
            if self._payments is None:
                raise RuntimeError(
                    "PaymentService must be configured on ApprovalService for settlement"
                )

            to_merchant = str(hold.payload.get("to_merchant") or hold.payload.get("merchant") or "")
            amount_minor = int(hold.payload.get("amount_minor") or hold.amount_minor)
            currency = str(hold.payload.get("currency") or hold.currency)

            outcome = await self._payments.settle_approved(
                agent_id=hold.agent_id,
                idem_key=hold.idem_key,
                to_merchant=to_merchant,
                amount_minor=amount_minor,
                currency=currency,
            )

            # Record audit "hold.settled" in its own independent UoW
            async with UnitOfWork(self._pool) as uow:
                await audit.record(
                    uow.connection,
                    actor_sub=voter_sub,
                    actor_role=voter_role,
                    action="hold.settled",
                    target_type="agent",
                    target_id=str(hold.agent_id),
                    details={
                        "hold_id": str(hold.hold_id),
                        "tx_id": str(outcome.tx_id),
                    },
                )

            await self._notifier.notify_hold_settled(hold, outcome)
            return VoteOutcome(
                status="approved_settled",
                votes_for=votes_for,
                votes_against=votes_against,
            )

        return VoteOutcome(
            status="counted",
            votes_for=votes_for,
            votes_against=votes_against,
        )


# ==============================================================================
# APPROVALS WORKER (NOTIFICATION & CRASH-HEAL SWEEP)
# ==============================================================================
@dataclass(frozen=True, slots=True)
class ApprovalWorkItem:
    """Item to be processed by ApprovalsWorker."""

    kind: Literal["notify_pending", "sweep_settle"]
    hold: HoldRecord


class ApprovalsWorker(Worker):
    """Continuous background worker for hold notification and crash-heal settlement."""

    def __init__(
        self,
        pool: asyncpg.Pool,
        bus: EventBus,
        notifier: AdminNotifier,
        payments: PaymentService,
        *,
        valkey: Any = None,
        poll_interval_s: float = 10.0,
        batch_size: int = 50,
        grace_seconds: float = 60.0,
        stop: asyncio.Event | None = None,
        sleeper: Callable[[float], Coroutine[Any, Any, None]] = asyncio.sleep,
        time_fn: Callable[[], datetime] = lambda: datetime.now(UTC),
    ) -> None:
        super().__init__(
            name="approvals_worker",
            pool=pool,
            valkey=valkey,
            bus=bus,
            poll_interval_s=poll_interval_s,
            batch_size=batch_size,
            stop=stop,
            sleeper=sleeper,
        )
        self._notifier = notifier
        self._payments = payments
        self._grace_seconds = grace_seconds
        self._time_fn = time_fn

    async def poll(self) -> Sequence[ApprovalWorkItem]:
        """Poll for unnotified pending holds and approved holds awaiting settlement."""
        items: list[ApprovalWorkItem] = []

        # (a) Unnotified pending holds
        async with self.pool.acquire() as conn:
            pending_rows = await conn.fetch(
                """
                SELECT
                    hold_id, agent_id, idem_key, amount_minor, currency,
                    reason, status, payload, created_at, updated_at
                FROM payment_holds
                WHERE status = 'pending' AND notified_at IS NULL
                ORDER BY created_at ASC
                LIMIT $1;
                """,
                self.batch_size,
            )

            for r in pending_rows:
                raw_payload = r["payload"]
                payload_data = (
                    orjson.loads(raw_payload)
                    if isinstance(raw_payload, (str, bytes))
                    else dict(raw_payload)
                )
                hold = HoldRecord(
                    hold_id=r["hold_id"],
                    agent_id=r["agent_id"],
                    idem_key=r["idem_key"],
                    amount_minor=r["amount_minor"],
                    currency=r["currency"],
                    reason=r["reason"],
                    status=str(r["status"]),
                    created_at=r["created_at"],
                    payload=payload_data,
                    updated_at=r["updated_at"],
                )
                items.append(ApprovalWorkItem(kind="notify_pending", hold=hold))

            # (b) Approved holds older than grace period (the crash-heal sweep)
            cutoff = self._time_fn() - timedelta(seconds=self._grace_seconds)
            approved_rows = await conn.fetch(
                """
                SELECT
                    hold_id, agent_id, idem_key, amount_minor, currency,
                    reason, status, payload, created_at, updated_at
                FROM payment_holds
                WHERE status = 'approved' AND updated_at < $1
                ORDER BY updated_at ASC
                LIMIT $2;
                """,
                cutoff,
                self.batch_size,
            )

            for r in approved_rows:
                raw_payload = r["payload"]
                payload_data = (
                    orjson.loads(raw_payload)
                    if isinstance(raw_payload, (str, bytes))
                    else dict(raw_payload)
                )
                hold = HoldRecord(
                    hold_id=r["hold_id"],
                    agent_id=r["agent_id"],
                    idem_key=r["idem_key"],
                    amount_minor=r["amount_minor"],
                    currency=r["currency"],
                    reason=r["reason"],
                    status=str(r["status"]),
                    created_at=r["created_at"],
                    payload=payload_data,
                    updated_at=r["updated_at"],
                )
                items.append(ApprovalWorkItem(kind="sweep_settle", hold=hold))

        return items

    async def process(self, batch: Sequence[Any]) -> None:
        """Process polled notifications and crash-heal sweep settlements."""
        # The worker is an automated operational mechanism, NEVER a decision-maker.
        # It never votes on holds; it only executes notifications and crash healing.
        for item in batch:
            if not isinstance(item, ApprovalWorkItem):
                continue

            if item.kind == "notify_pending":
                await self._process_notify_pending(item.hold)
            elif item.kind == "sweep_settle":
                await self._process_sweep_settle(item.hold)

    async def _process_notify_pending(self, hold: HoldRecord) -> None:
        """Dispatch operator notification and record notified_at marker."""
        await self._notifier.notify_hold_pending(hold)
        async with self.pool.acquire() as conn:
            await conn.execute(
                """
                UPDATE payment_holds
                SET notified_at = now()
                WHERE hold_id = $1 AND notified_at IS NULL;
                """,
                hold.hold_id,
            )

    async def _process_sweep_settle(self, hold: HoldRecord) -> None:
        """Probe idempotency state and execute crash-heal settlement if still pending."""
        async with self.pool.acquire() as conn:
            reservation = await idempotency_lookup(conn, hold.agent_id, hold.idem_key)

        if reservation is not None and reservation.outcome == ReservationOutcome.REPLAY:
            # COMPLETED with settled wire body; money already moved before crash. Skip.
            return

        to_merchant = str(hold.payload.get("to_merchant") or hold.payload.get("merchant") or "")
        amount_minor = int(hold.payload.get("amount_minor") or hold.amount_minor)
        currency = str(hold.payload.get("currency") or hold.currency)

        outcome = await self._payments.settle_approved(
            agent_id=hold.agent_id,
            idem_key=hold.idem_key,
            to_merchant=to_merchant,
            amount_minor=amount_minor,
            currency=currency,
        )

        async with UnitOfWork(self.pool) as uow:
            await audit.record(
                uow.connection,
                actor_sub="system:approvals_worker",
                actor_role="admin",
                action="hold.settled",
                target_type="agent",
                target_id=str(hold.agent_id),
                details={
                    "hold_id": str(hold.hold_id),
                    "tx_id": str(outcome.tx_id),
                    "source": "sweep",
                },
            )

        await self._notifier.notify_hold_settled(hold, outcome)

    async def run_once(self) -> int:
        """Execute a single poll and process cycle. Returns number of items processed."""
        batch = await self.poll()
        if batch:
            await self.process(batch)
        return len(batch)
